package by.yegorov.testdb.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import by.yegorov.testdb.db.model.DummyModel;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table DUMMY_MODEL.
 */
public class DummyModelDao extends AbstractDao<DummyModel, Long> {

    public static final String TABLENAME = "DUMMY_MODEL";

    /**
     * Properties of entity DummyModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DummyString = new Property(1, String.class, "dummyString", false, "DUMMY_STRING");
        public final static Property DummyLong = new Property(2, Long.class, "dummyLong", false, "DUMMY_LONG");
    }

    ;


    public DummyModelDao(DaoConfig config) {
        super(config);
    }

    public DummyModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'DUMMY_MODEL' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'DUMMY_STRING' TEXT," + // 1: dummyString
                "'DUMMY_LONG' INTEGER);"); // 2: dummyLong
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DUMMY_MODEL'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, DummyModel entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String dummyString = entity.getDummyString();
        if (dummyString != null) {
            stmt.bindString(2, dummyString);
        }

        Long dummyLong = entity.getDummyLong();
        if (dummyLong != null) {
            stmt.bindLong(3, dummyLong);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public DummyModel readEntity(Cursor cursor, int offset) {
        DummyModel entity = new DummyModel( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // dummyLong
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // dummyString

        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, DummyModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDummyString(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDummyLong(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(DummyModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(DummyModel entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
